apiVersion: v1
kind: Service
metadata:
  name: gateway-to-qa
  labels:
    component: web
    role: test-blue
spec:
  type: LoadBalancer
  selector:
    component: web
    role: blue
  ports:
    - port: 3000
      targetPort: 3000
      