apiVersion: v1
kind: Service
metadata:
  name: gateway-to-production
  labels:
    component: web
    role: green
    env: prod
spec:
  type: LoadBalancer
  selector:
    component: web
    role: green
  ports:
    - port: 3000
      targetPort: 3000
